config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  get 'books', to: 'books#index'

  get 'publisher/:publisher_id/books', to: 'books#publisher', as: 'publisher_books'
  get 'genre/:genre_id/books',         to: 'books#genre',     as: 'genre_books'
  get 'author/:author_id/books',       to: 'books#author',    as: 'author_books'
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books

  validates :first_name, presence: true
  validates :last_name, presence: true

  def name
    "#{first_name} #{last_name}"
  end

  def last_name_first
    "#{last_name}, #{first_name}"
  end

  def books_by_rating
    self.books.select("DISTINCT books.*, AVG(book_reviews.rating) AS rating").joins(:book_reviews).group("books.id").order("rating DESC")
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :publisher
  belongs_to :author
  belongs_to :genre

  has_many :book_reviews
  has_many :book_formats
  has_many :book_format_types, -> { distinct }, through: :book_formats

  validates :title, presence: true
  validates :genre_id, presence: true
  validates :author_id, presence: true
  validates :publisher_id, presence: true

  def format_types
    book_format_types.map(&:name).join(', ')
  end

  def author_name
    self.author.last_name_first
  end

  def average_rating
    book_reviews.map(&:rating).inject(0) { |sum, x| sum + x }.to_f / book_reviews.size
  end

  def self.search(query, options)
    if query
      if options.nil?
        title_only = false
        type_ids, physical = nil
      else
        options[:title_only] ? title_only = true : title_only = false
        options[:book_format_type_id] ? type_ids = options[:book_format_type_id] : type_ids = nil
        if options[:book_format_physical].nil?
          physical = nil
        else
          physical = options[:book_format_physical]
        end
      end

      conditions =  condition_query(title_only)

      if !physical.nil? and type_ids
        # only book formats selected and acording to it's physical boolean
        ids = options[:book_format_type_id].map(&:to_i) & BookFormatType.where(physical: physical).pluck(:id)
      elsif physical.nil? and type_ids
        # only book formats selected
        ids = options[:book_format_type_id].map(&:to_i)
      elsif !physical.nil? and type_ids.nil?
        # only the book formats acording to it's physical boolean
        ids = BookFormatType.where(physical: physical).pluck(:id)
      else
        ids = nil
      end

      begin
        if title_only and ids.nil?
          self.select("DISTINCT books.*, AVG(book_reviews.rating) AS rating").joins(:book_reviews).where(conditions, "%#{query.downcase}%").group("books.id").order("rating DESC")
        elsif !title_only and ids.nil?
          self.select("DISTINCT books.*, AVG(book_reviews.rating) AS rating").joins(:book_reviews).joins(:author).joins(:publisher).where(conditions, "%#{query.downcase}%", query.downcase, query.downcase).group("books.id").order("rating DESC")
        elsif title_only and ids
          conditions += " AND book_format_types.id IN (#{ids.join(', ')})"
          self.select("DISTINCT books.*, AVG(book_reviews.rating) AS rating").joins(:book_reviews).joins(:book_format_types).where(conditions, "%#{query.downcase}%").group("books.id").order("rating DESC")
        elsif !title_only and ids
          conditions = "(#{conditions}) AND book_format_types.id IN (#{ids.join(', ')})"
          self.select("DISTINCT books.*, AVG(book_reviews.rating) AS rating").joins(:book_reviews).joins(:author).joins(:publisher).joins(:book_format_types).where(conditions, "%#{query.downcase}%", query.downcase, query.downcase).group("books.id").order("rating DESC")
        end
      rescue
        none # Did not find any books matching search criteria
      end
    else
      all_by_rating "DESC"
    end
  end

  def self.highest_rating
    all_by_rating("DESC").first
  end

  def self.lowest_rating
    all_by_rating("ASC").first
  end

  def self.all_by_rating order
    self.select("DISTINCT books.*, AVG(book_reviews.rating) AS rating").joins(:book_reviews).group("books.id").order("rating #{order}")
  end

private

  def self.title_conditions
    "lower(books.title) LIKE ?"
  end

  def self.author_conditions
    "lower(authors.last_name) = ?"
  end

  def self.publisher_conditions
    "lower(publishers.name) = ?"
  end

  def self.condition_query title_only
    title_only ? title_conditions : [title_conditions, author_conditions, publisher_conditions].join(' OR ')
  end

end

app/models/book_format.rb
class BookFormat < ActiveRecord::Base
  belongs_to :book
  belongs_to :book_format_type

  validates :book_id, presence: true
  validates :book_format_type_id, presence: true
end

app/models/book_format_type.rb
class BookFormatType < ActiveRecord::Base
  has_many :book_formats
  has_many :books, -> { distinct }, through: :book_formats

  validates :name, presence: true
  validates :name, uniqueness: true

  before_create :set_defualt_physical

  protected

  def set_defualt_physical
     self.physical = true if self.physical.nil?
   end
end

app/models/book_review.rb
class BookReview < ActiveRecord::Base
  belongs_to :book

  validates :book_id, presence: true
  validates :rating, presence: true
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :books
  validates :name, presence: true
  validates :name, uniqueness: true

  def books_by_rating
    self.books.select("DISTINCT books.*, AVG(book_reviews.rating) AS rating").joins(:book_reviews).group("books.id").order("rating DESC")
  end
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :books

  validates :name, presence: true
  validates :name, uniqueness: true

  def books_by_rating
    self.books.select("DISTINCT books.*, AVG(book_reviews.rating) AS rating").joins(:book_reviews).group("books.id").order("rating DESC")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    if params[:book].nil?
      options = nil
    else
      options = get_options(params[:title_only], params[:physical], params[:book][:book_format_type_ids])
    end

    @books = Book.search(params[:search], options).paginate(:page => params[:page], :per_page => 10)
  end

  def publisher
    @publisher = Publisher.find(params[:publisher_id])
    @books = @publisher.books_by_rating.paginate(:page => params[:page], :per_page => 10)
  end

  def genre
    @genre = Genre.find(params[:genre_id])
    @books = @genre.books_by_rating.paginate(:page => params[:page], :per_page => 10)
  end

  def author
    @author = Author.find(params[:author_id])
    @books = @author.books_by_rating.paginate(:page => params[:page], :per_page => 10)
  end

protected

  def get_options(title_only, physical, format_type_ids)
    options = {}
    options[:title_only] = true unless title_only.nil?
    options[:book_format_type_id] = format_type_ids[0..-2] if format_type_ids.size > 1
    unless physical.nil?
      physical == 'yes' ? options[:book_format_physical] = true : options[:book_format_physical] = false
    end
    if options.empty?
      return nil
    else
      return options
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
<%= will_paginate @books %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Publisher</th>
      <th>Author</th>
      <th>Genre</th>
      <th>Rating</th>
      <th>Available in</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= link_to book.publisher.name, publisher_books_path(book.publisher) %></td>
        <td><%= link_to book.author.name, author_books_path(book.author) %></td>
        <td><%= link_to book.genre.name, genre_books_path(book.genre) %></td>
        <td><%= book.average_rating %></td>
        <td><%= book.format_types %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/author.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%= "#{@author.name}'s books" %></h1>
</div>

<%= link_to 'Search', root_path %>

<%= render 'list' %>

app/views/books/genre.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%= "#{@genre.name}" %></h1>
</div>

<%= link_to 'Search', root_path %>

<%= render 'list' %>

app/views/books/index.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= form_for books_path, method: 'get' do  %>
  <p> <%= text_field_tag :search, params[:search] %> <%= check_box_tag 'title_only', 'yes', false %> Title only <%= submit_tag "Search", name: nil, :class => 'btn btn-primary'  %> </p>

<a href="javascript:hideshow(document.getElementById('options'))" id="show_hide">Search options</a>
<div id="options" style="display: none">
  <p><%= radio_button_tag 'physical', 'yes', false %> Physical only formats
  <%= radio_button_tag 'physical', 'no', false %> Digital only formats</p>
  <%= collection_check_boxes(:book, :book_format_type_ids, BookFormatType.all, :id, :name) do |b| %>
    <%= b.check_box %>
    <%= b.label %>
  <% end %>
  </div>
<% end %>

<%= render 'list' %>

app/views/books/publisher.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%= "#{@publisher.name}" %></h1>
</div>

<%= link_to 'Search', root_path %>

<%= render 'list' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Terakeet" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>by <a href="http://www.github.com/brenodamata/terakeet_challenge">Breno</a></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>